version: "3.9"

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    ports:
      - "4550:4550"
    depends_on:
      - twif-postgres
    restart: always

    volumes:
      - ./backend:/backend  # Монтируем директорию app с хоста в контейнер
      - ./backend/media:/backend/media  # Монтируем директорию app с хоста в контейнер

    working_dir: /backend

  twif-postgres:
    image: "postgres:13.3-alpine"
    container_name: twif-postgres
    volumes:
      - twif-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: twif

      POSTGRES_USER: twif
      POSTGRES_PASSWORD: twif
    networks:
      - dev

  redis:
    image: "redis:latest"
    ports:
    - "6379:6379"
    networks:
    - dev

  background:
    build:
      context: ./background
    environment:
      - REDIS_HOST=redis
      - BOT_TOKEN=7396897324:AAHzNa_ncI4sf0hkg8M0txRt9KWZSnXFqC0
      - PYTHONUNBUFFERED=1
      - BACKEND_HOST=https://6adc-178-47-140-82.ngrok-free.app
    networks:
      - dev
    depends_on:
      - redis
    restart: always
    working_dir: /background
volumes:
  twif-data:
